version: "3.9"

services:
  django:
    build:
      context: ./src/backend
    command: gunicorn --worker-tmp-dir /dev/shm --workers=2 --threads=2 --bind 0.0.0.0:8000 skeleton.wsgi:application
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - VIRTUAL_HOST=${VIRTUAL_HOST_DJANGO}
      - ALLOWED_HOSTS=${VIRTUAL_HOST_DJANGO}
      - DEBUG=False
      - SECRET_KEY
    expose:
      - 8000
    volumes:
      - ./src/backend/:/app/
    networks:
      - app
      - proxy_<your-project-name>_prod
  
  postgres:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
    postgres:

networks:
    app:
    proxy_<your-project-name>_dev:
        external: true
